apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: catalog-service 

spec: 
  template:
    spec: 
      containers:
        - name: catalog-service 
          resources: 
            requests: 
              cpu: 100m
              memory: 256Mi
            limits: 
              cpu: 2
              memory: 700Mi