apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
        - name: catalog-service
          resources:
            requests:
              memory: 256Mi
              cpu: "0.5"
            limits:
              memory: 512Mi
              cpu: "1"
